### ISSUE TITLE
Attachment Demographics Report - Dec21 FMB versions internal inconsistencies between PDC001 and PDC1738

### ISSUE THREAD

**Issue by CCMcGuinness** [PDCbc/hapi#29]
The Demographics report created by FMB Dec 21 for attachment is essential "good to go" except for internal consistencies between the all group and all network totals for patient counts.  I can't explain the  differences.  For example.  The demographics report, based on query PDC 001) for Vancouver provides N value for group at 17, 154 and all network at 42, 457.  PDC 001 - count of active patients (as far as I can tell from the query code) while the attached active report, based on query 1738) for Vancouver provides N value for group at 18, 791 and all network at 65,899.  I want this difference to be a result of a different definition for patient that is being counted, but can`t confirm that is true.  The activepatient function is internal inconsistencies between what is commented in the code and what the code appears to be doing.....ie encounters condition within last 36 months vs 24 months - is medications also being counted.....and then how is activepatients function being used if at all in the PDC001 metric....very confusing stuff....also related to issues with PDC 831 which is supposed to be an active patient count, but doesn`t utilize the medication constraint as in activepatient function....but this is another story...

[YVRattachmentAttachedPatientsReportJan11.xlsx](https://github.com/PDCbc/hapi/files/86507/YVRattachmentAttachedPatientsReportJan11.xlsx)
[YVRattachmentDemographicsReportJan11.xlsx](https://github.com/PDCbc/hapi/files/86508/YVRattachmentDemographicsReportJan11.xlsx)

**Comment by CCMcGuinness** [comment]
The change made to PDC 001 helped with the internal inconsistencies, but there is still about 10% difference between total active patient count with PDC 001 and numerator for PDC 1738 - suspect it has to do with the use of !activepatient records being removed explicitly in PDC 001 and not in PDC 1738 - note any changes must be applied to both the realtime and the retro versions of the queries.

**Comment by DerekRoberts** [comment]
"Make 001 match retro-001 and master attachment's NETWORK total."
