### ISSUE TITLE
Attachment Reports Empty

### ISSUE THREAD

**Issue by DerekRoberts** [PDCbc/hapi#38]

**Comment by CCMcGuinness** [comment]
which attachment reports - remember there are two sets of these reports.  One meant for an external (non contributor to the system) = Master Attachment reports.  and the second set meant for the individual physician end user - Attachment prototype reports which are available on via the interface and as currently configured are not exactly correct.......ie need some revision.  The Master reports include data from all members of a particular attachment group and are available external to the interface........currently the two sets of reports while they have similar names are not the SAME reports........
